/**
 * Generates .well-known/xrp-ledger.toml for Bithomp domain verification.
 * Uses XRPL_WALLET_ADDRESS (project operator) from .env — never secrets.
 */
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const rootDir = path.resolve(__dirname, '..');
const envPath = path.join(rootDir, '.env');
const outDir = path.join(rootDir, '.well-known');
const outPath = path.join(outDir, 'xrp-ledger.toml');

function parseEnvFile(filePath) {
  if (!fs.existsSync(filePath)) return {};
  const lines = fs.readFileSync(filePath, 'utf8').split(/\r?\n/);
  const env = {};
  for (const line of lines) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;
    const eq = trimmed.indexOf('=');
    if (eq === -1) continue;
    const key = trimmed.slice(0, eq).trim();
    let value = trimmed.slice(eq + 1).trim();
    if ((value.startsWith('"') && value.endsWith('"')) || (value.startsWith("'") && value.endsWith("'"))) {
      value = value.slice(1, -1);
    }
    env[key] = value;
  }
  return env;
}

function pick(env, key, fallback = '') {
  return env[key] ?? process.env[key] ?? fallback;
}

const fileEnv = parseEnvFile(envPath);
const merged = { ...process.env, ...fileEnv };

const appUrl = pick(merged, 'APP_URL', 'https://mosaico-criptografico.vercel.app').replace(/\/$/, '');
const operatorAddress = pick(merged, 'XRPL_WALLET_ADDRESS', '').trim();
const contactEmail = pick(merged, 'PROJECT_CONTACT_EMAIL', '').trim();
const twitter = pick(merged, 'PROJECT_TWITTER', '@CuevazaArt').trim();
const modified = new Date().toISOString().slice(0, 10);

const lines = [
  '# Cryptographic Mosaic — Mosaic Keychain',
  '# Auto-generated by scripts/generate-toml.js — run: npm run build',
  `# Last modified: ${modified}`,
  '',
  '[METADATA]',
  `modified = "${modified}"`,
  'expires = "2099-12-31T23:59:59.000Z"',
  '',
  '[ORGANIZATION]',
  'name = "Cryptographic Mosaic"',
  'desc = "Open-source XRPL sensory identity utility — visual and acoustic keychain anchored via self-issued Soulbound NFTs (taxon 1001). Not an airdrop or pass."',
  `website = "${appUrl}"`,
  `github = "https://github.com/CuevazaArt/mosaico-criptografico"`,
  `docs = "${appUrl}/verify"`,
  `trust_issue = "https://github.com/CuevazaArt/mosaico-criptografico/blob/main/XAMAN_TRUST_ISSUE.md"`,
];

if (twitter) {
  lines.push(`twitter = "${twitter}"`);
}
if (contactEmail) {
  lines.push(`email = "${contactEmail}"`);
}

lines.push(
  '',
  '# Mosaic Keychain NFT protocol (self-mint utility — Issuer must equal Owner)',
  '[NFT_PROTOCOL.MOSAIC_KEYCHAIN]',
  'taxon = 1001',
  'transferable = false',
  'issuer_must_equal_owner = true',
  `metadata_uri_template = "${appUrl}/api/nft/{address}"`,
  `verify_page = "${appUrl}/verify"`,
  '',
);

if (operatorAddress && /^r[1-9A-HJ-NP-Za-km-z]{24,34}$/.test(operatorAddress)) {
  lines.push(
    '[[ACCOUNTS]]',
    `address = "${operatorAddress}"`,
    'desc = "Cryptographic Mosaic project operator (service identity — not end-user NFT issuer)"',
    '',
  );
} else {
  lines.push(
    '# [[ACCOUNTS]] — set XRPL_WALLET_ADDRESS in .env and redeploy to publish operator account',
    '',
  );
}

fs.mkdirSync(outDir, { recursive: true });
fs.writeFileSync(outPath, `${lines.join('\n')}\n`, 'utf8');

console.log(`[toml] Generated ${path.relative(rootDir, outPath)}`);
if (!operatorAddress) {
  console.warn('[toml] WARNING: XRPL_WALLET_ADDRESS is empty — add your project operator r-address to .env before Bithomp verification.');
}
