/**
 * Reads .env and generates config.runtime.js for browser + deployment metadata.
 * Public values only — XUMM_API_SECRET never goes to the client bundle.
 */
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const rootDir = path.resolve(__dirname, '..');
const envPath = path.join(rootDir, '.env');
const outputPath = path.join(rootDir, 'config.runtime.js');

function parseEnvFile(filePath) {
  if (!fs.existsSync(filePath)) return {};
  const lines = fs.readFileSync(filePath, 'utf8').split(/\r?\n/);
  const env = {};
  for (const line of lines) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;
    const eq = trimmed.indexOf('=');
    if (eq === -1) continue;
    const key = trimmed.slice(0, eq).trim();
    let value = trimmed.slice(eq + 1).trim();
    if ((value.startsWith('"') && value.endsWith('"')) || (value.startsWith("'") && value.endsWith("'"))) {
      value = value.slice(1, -1);
    }
    env[key] = value;
  }
  return env;
}

function pick(env, key, fallback = '') {
  return env[key] ?? process.env[key] ?? fallback;
}

const fileEnv = parseEnvFile(envPath);
const deploymentMode = pick(fileEnv, 'DEPLOYMENT_MODE', 'development');
const isProduction = deploymentMode === 'production';

const enableLocalDemoRaw = pick(fileEnv, 'ENABLE_LOCAL_DEMO', '');
const enableLocalDemo = enableLocalDemoRaw === 'true'
  ? true
  : enableLocalDemoRaw === 'false'
    ? false
    : !isProduction;

const config = {
  deploymentMode,
  defaultNetwork: pick(fileEnv, 'DEFAULT_XRPL_NETWORK', isProduction ? 'mainnet' : 'testnet'),
  appUrl: pick(fileEnv, 'APP_URL', 'http://localhost:3000'),
  xummApiKey: pick(fileEnv, 'XUMM_API_KEY', ''),
  xummBackendEnabled: Boolean(pick(fileEnv, 'XUMM_API_KEY') && pick(fileEnv, 'XUMM_API_SECRET')),
  enableLocalDemo,
  defaultWallet: isProduction ? 'gem' : 'local',
  sampleXrplAddress: 'rG1QQv2dh2AGTf5gZUXyZEaXcRmGRHsGQE',
  version: pick(fileEnv, 'npm_package_version', '3.1.1')
};

const output = `// AUTO-GENERATED by scripts/generate-config.js — do not edit manually.
// Regenerate: npm run config
window.__APP_CONFIG__ = ${JSON.stringify(config, null, 2)};
`;

fs.writeFileSync(outputPath, output, 'utf8');

console.log(`[config] Generated ${path.relative(rootDir, outputPath)}`);
console.log(`[config] Mode: ${config.deploymentMode} | Network: ${config.defaultNetwork} | Xaman: ${config.xummApiKey ? 'configured' : 'missing API key'}`);

if (isProduction && !config.xummApiKey) {
  console.warn('[config] WARNING: XUMM_API_KEY is empty — Xaman wallet will not work in production.');
}
